import '@/global/preset/reset.css'

export const metadata = {
  title: 'Create Next Apple',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
