import '@/design/preset/reset.css'
import Footer from './(footer)'
import { getDictionary } from '@/../get-dictionary'
import type { Locale } from '@/../i18n-config'
import LocaleSwitcher from '@/components/i18n/locale-switcher'
import './layout.scss'
import Navigation from './Navigation'
import Header from './Header'

import { goToId } from '@/model/utilities/viewAction'
import Link from 'next/link'
import Video from '@/components/videoWrap/FullScreenVideoWrap'

export const metadata = {
  title: '제목',
  description: 'Generated by create next app',
}

type Props = { params: { lang: Locale }; children: React.ReactNode }

const RootLayout = async ({ params: { lang }, children }: Props) => {
  const dictionary = await getDictionary(lang)

  return (
    <div>
      <LocaleSwitcher />
      <Navigation />
      <Header />
      <Video src="/video/166808.mp4" />
      <p>Test는 /test로</p>
      <Link href="/test">바로가기</Link>
    </div>
  )
}

export default RootLayout
