import '@/design/preset/reset.css'
import Footer from './(footer)'
import type { Locale } from '@/../i18n-config'
import LocaleSwitcher from '@/components/i18n/locale-switcher'
import styles from './layout.module.scss'
import Navigation from './HashNavigation'
import Header from './Header'
import RouterEvent from './RouterEvent'
import Link from 'next/link'

export const metadata = {
  title: '제목',
  description: 'Generated by create next app',
}

type Props = { params: { lang: Locale }; children: React.ReactNode }
const list = ['1', '2', '3', '4', '5', '6']

const RootLayout = ({ params: { lang }, children }: Props) => {
  return (
    <div>
      <LocaleSwitcher lang={lang} />
      <Navigation />
      <RouterEvent />
      <Header />
      <p>Current locale: {lang}</p>
      <Link id="nav-company" className={styles.link} href="/#company">
        기업소개
      </Link>

      <h1>로고</h1>
      <p>id 기준으로 추적되게 + 네비게이팅도 되게 해보자</p>
      {Array.from({ length: 10 }).map((item, index) => {
        return (
          <h2 className={styles.h2} key={index} id={`${index}`}>
            {index}
          </h2>
        )
      })}

      {children}
      <Footer />
    </div>
  )
}

export default RootLayout
