import '@/design/preset/reset.css'
import { getDictionary } from '@/../get-dictionary'
import type { Locale } from '@/../i18n-config'
import Navigation from './Navigation'
import Scroll from './ScrollEvents'
import Header from './(header)'

import Link from 'next/link'
import './layout.scss'

export const metadata = {
  title: '제목',
  description: 'Generated by create next app',
}

// 전부 공유 되야하는 컴포넌트임
// header와 footer , 메타데이터, og

type Props = { params: { lang: Locale }; children: React.ReactNode }

const RootLayout = async ({ params: { lang }, children }: Props) => {
  return (
    <>
      {/* <Navigation /> */}
      <Header lang={lang} />

      <Scroll />
      {children}
    </>
  )
}

export default RootLayout
