import '@/global/preset/reset.css'

export const metadata = {
  title: 'Create Header',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <>헤더어어어어{children}</>
}
